### ISSUE TITLE
Lock in place not saved

### ISSUE THREAD

**Issue by ozyre** [VictorGrycuk/streamdeck-magnifier#4] opened 2023-12-16 14:09 UTC
Hi. 

Options for title, zoom size or enabling crosshair is saved in the profile. But although holding down the key for 2 seconds locks the **view in place**, this option is reverted after reloading the profile and **not saved**.

I am not sure if this is the intended way, or a bug on my end. 
And if this is not a bug, is it possible to implement this option, as locking the position is the most useful feature of this plugin?

I am using a **Stream Deck MK.2** and software version **6.4.1.19697** 

Thank you.

**Comment by VictorGrycuk** [comment] 2023-12-16 16:53
Hi @ozyre, thanks for reporting it.
I will have a look at it, see if I can reproduce it, and try to find a solution, if possible.

**Comment by ozyre** [comment] 2023-12-16 17:52
No problem. 
I tried both dual monitor and single monitor setups btw but the problem persists. Running on Windows 11.
Besides switching profiles, **entering a folder** and exiting resets the position too.
Let me know if you need any other info or anything else to test.

**Comment by VictorGrycuk** [comment] 2023-12-20 00:57
I was able to reproduce the problem.
The problem is that, unlike the other options, the location is not saved to the StreamDeck configuration, because it's not part of the configuration settings.

I will see what I can do, but I think it's doable.

**Comment by VictorGrycuk** [comment] 2023-12-29 01:53
@ozyre I think I got it working.
In the property inspector now appear to two new configuration, the `Is Locked` and `Location`.

![image](https://github.com/VictorGrycuk/streamdeck-magnifier/assets/39467613/900e40f0-ac10-4588-bae9-420324de8d01)
After pressing the key for two seconds, both should be updated with the status of locked/unlocked and the mouse location. The configuration should be saved and recovered after changing profiles.
It shouldn't be necessary to manually set this configuration, unless you want to set the coordinate manually.

I am attaching a version with this fix. Just change `.zip` to `.streamDeckPlugin` and it will let you install it.
Please let me know if this works as intended, so I can make a proper release of the new version.

[com.victorgrycuk.magnifier.zip](https://github.com/VictorGrycuk/streamdeck-magnifier/files/13790359/com.victorgrycuk.magnifier.zip)

**Comment by ozyre** [comment] 2023-12-29 08:17
Thank you. I am at work now and I will test it later today as soon as I go back home and will let you know.

**Comment by ozyre** [comment] 2023-12-29 15:53
Just did some tests and I can confirm position is saved now, after restarting the software, changing pages, changing profiles and also entering into a folder. 
So far It seems working great. I will let you know if I encounter any bugs in the future. 👍

**Comment by VictorGrycuk** [comment] 2023-12-29 20:13
Thanks for letting me know!
I will close the issue and release a new version in the next days.

Don't hesitate to open a new issue.

**Closed as completed by VictorGrycuk** 2023-12-29 20:13 UTC
