### ISSUE TITLE
Will not follow cursor onto left monitor

### ISSUE THREAD

**Issue by DeltaR9A2** [VictorGrycuk/streamdeck-magnifier#2] opened 2021-06-15 17:56 UTC
I noticed that the magnifier stops at the left edge of the center screen on my three monitors. I think the problem is here: https://github.com/VictorGrycuk/streamdeck-magnifier/blob/114fa5ad1bb0850d5b5a5d779fe803c1ef1e6f4d/streamdeck-magnifier/streamdeck-magnifier/Helpers/ImageHelper.cs#L37

The code clamps the image source location to never be less than zero in either X or Y, but my understanding is that the screen coordinate (0,0) is the top left corner of the "primary display", so additional displays positioned above and/or left of the primary will use negative coordinates. I suspect that just letting the value follow the mouse cursor into the negative would fix this problem, but I don't have any experience with C# or Microsoft's development tools so I can't test it myself.

**Comment by VictorGrycuk** [comment] 2021-07-10 20:56
Thanks @JayThirtySeven for finding this.
I will try to reproduce this by setting a secondary display, with the right screen being the main one.

I will let you know when a fix available.

**Comment by VictorGrycuk** [comment] 2023-04-24 21:30
Hi @DeltaR9A2, for the very late response.
You were right, allowing it to go into the negative fixes the issue.

I will be releasing a new version in the next days.

**Comment by VictorGrycuk** [comment] 2023-12-31 00:49
@DeltaR9A2 I guess I never confirmed the release of the version and closed this issue, but the problem was closed on version [1.3.0](https://github.com/VictorGrycuk/streamdeck-magnifier/releases/tag/v1.3.0).

**Closed as completed by VictorGrycuk** 2023-12-31 00:49 UTC
